[package]
name = "intl-rs"
version = "0.1.0"
authors = ["longyun <ly1169134156@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
